
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
  issue_comment:                                     
    types: [created, edited]


stages:
- stage: Dev
  jobs:
  - job: DeployToDev
    if: contains(github.event.comment.body, '/test')
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo Deploying to Dev
    - task: Approval
      inputs:
        notifyUsers: |
          lysanne.l.fernandes@kipi.bi

- stage: QA
  jobs:
  - job: DeployToQA
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo Deploying to QA
    - task: Approval
      inputs:
        notifyUsers: |
          lysanne.l.fernandes@kipi.bi

