name: Continuous Integration

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  pull_request:
      branches:
        - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Verify
      run: |
        echo "${{ github.event_name }} ok"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover
