name: Test

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test NEw
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2